# Generated by Django 5.2.4 on 2025-07-20 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity_received',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество получено'),
        ),
    ]
