# Generated by Django 5.2.4 on 2025-07-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0002_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('sale_type', models.CharField(choices=[('regular', 'Обычная продажа'), ('order', 'Заказная позиция')], default='regular', max_length=10, verbose_name='Тип продажи')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма продажи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.customer', verbose_name='Клиент')),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.requestitem', verbose_name='Заказная позиция')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отмены')),
                ('reason', models.TextField(verbose_name='Причина отмены')),
                ('restored_units', models.ManyToManyField(to='unit.productunit', verbose_name='Возвращённые единицы')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Отмена продажи',
                'verbose_name_plural': 'Отмены продаж',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическая цена')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Отменена')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.productunit', verbose_name='Единица товара')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Позиция продажи',
                'verbose_name_plural': 'Позиции продаж',
            },
        ),
    ]
