# Generated by Django 5.2.4 on 2025-07-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('in_request', 'В заявке'), ('in_request_cancelled', 'В заявке - отменен'), ('in_store', 'В магазине'), ('sold', 'Продан'), ('broken', 'Сломан'), ('lost', 'Утерян'), ('transferred', 'Передан')], default='in_request', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Единица товара',
                'verbose_name_plural': 'Единицы товаров',
            },
        ),
    ]
