# Generated by Django 5.2.4 on 2025-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_category_description_category_slug_and_more'),
        ('unit', '0002_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='sale_date',
            field=models.DateField(blank=True, help_text='Фактическая дата продажи единицы товара', null=True, verbose_name='Дата продажи'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая цена, по которой продан товар', max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['status', 'product'], name='unit_produc_status_41544a_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['sale_date'], name='unit_produc_sale_da_e3babf_idx'),
        ),
    ]
