# Generated by Django 5.2.4 on 2025-07-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_productunit_sale_date_productunit_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='sale_date',
            field=models.DateField(blank=True, help_text='Фактическая дата продажи (если товар продан)', null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена продажи (если товар продан)', max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
    ]
